name: CI demo

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run Tests
        run: pytest app

      - name: Run Ruff
        run: ruff check app

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/devops-demo:latest ./app

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/devops-demo:latest